# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json tsconfig.json ./

# Copy source code
COPY src ./src

# Build the TypeScript project
RUN npm install --ignore-scripts && npm run build

# Default command to start the MCP server
CMD ["node", "dist/index.js"]
